/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jnireflection_bindings_JNIReflection */

#ifndef _Included_com_jnireflection_bindings_JNIReflection
#define _Included_com_jnireflection_bindings_JNIReflection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    getStaticObject
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_jnireflection_bindings_JNIReflection_getStaticObject
        (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    setStaticObject
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnireflection_bindings_JNIReflection_setStaticObject
        (JNIEnv *, jclass, jobject, jstring, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    getObject
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_jnireflection_bindings_JNIReflection_getObject
        (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    setObject
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_jnireflection_bindings_JNIReflection_setObject
        (JNIEnv *, jclass, jobject, jstring, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    getInstances
 * Signature: (Ljava/lang/String;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jnireflection_bindings_JNIReflection_getInstances
        (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
