/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_Main */

#ifndef _Included_test_Main
#define _Included_test_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
* Class:     test_Main
* Method:    printHello
* Signature: ()V
*/
JNIEXPORT void JNICALL Java_test_Main_printHello
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
