/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jnireflection_bindings_JNIReflection */

#ifndef _Included_com_jnireflection_bindings_JNIReflection
#define _Included_com_jnireflection_bindings_JNIReflection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    getStaticObject
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_jnireflection_bindings_JNIReflection_getStaticObject
        (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    setStaticObject
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnireflection_bindings_JNIReflection_setStaticObject
        (JNIEnv *, jclass, jobject, jstring, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    getStaticByte
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)B
 */
JNIEXPORT jbyte JNICALL Java_com_jnireflection_bindings_JNIReflection_getStaticByte
        (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    setStaticByte
 * Signature: (BLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnireflection_bindings_JNIReflection_setStaticByte
        (JNIEnv *, jclass, jbyte, jstring, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    getStaticShort
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_com_jnireflection_bindings_JNIReflection_getStaticShort
        (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    setStaticShort
 * Signature: (SLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnireflection_bindings_JNIReflection_setStaticShort
        (JNIEnv *, jclass, jshort, jstring, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    getStaticInt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jnireflection_bindings_JNIReflection_getStaticInt
        (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    setStaticInt
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnireflection_bindings_JNIReflection_setStaticInt
        (JNIEnv *, jclass, jint, jstring, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    getStaticLong
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_jnireflection_bindings_JNIReflection_getStaticLong
        (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    setStaticLong
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnireflection_bindings_JNIReflection_setStaticLong
        (JNIEnv *, jclass, jlong, jstring, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    getStaticFloat
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_com_jnireflection_bindings_JNIReflection_getStaticFloat
        (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    setStaticFloat
 * Signature: (FLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnireflection_bindings_JNIReflection_setStaticFloat
        (JNIEnv *, jclass, jfloat, jstring, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    getStaticDouble
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_com_jnireflection_bindings_JNIReflection_getStaticDouble
        (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    setStaticDouble
 * Signature: (DLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnireflection_bindings_JNIReflection_setStaticDouble
        (JNIEnv *, jclass, jdouble, jstring, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    getStaticBoolean
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jnireflection_bindings_JNIReflection_getStaticBoolean
        (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    setStaticBoolean
 * Signature: (ZLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnireflection_bindings_JNIReflection_setStaticBoolean
        (JNIEnv *, jclass, jboolean, jstring, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    getStaticChar
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)C
 */
JNIEXPORT jchar JNICALL Java_com_jnireflection_bindings_JNIReflection_getStaticChar
        (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    setStaticChar
 * Signature: (CLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnireflection_bindings_JNIReflection_setStaticChar
        (JNIEnv *, jclass, jchar, jstring, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    getInstanceObject
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_jnireflection_bindings_JNIReflection_getInstanceObject
        (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    setInstanceObject
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnireflection_bindings_JNIReflection_setInstanceObject
        (JNIEnv *, jclass, jobject, jobject, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    getInstanceByte
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)B
 */
JNIEXPORT jbyte JNICALL Java_com_jnireflection_bindings_JNIReflection_getInstanceByte
        (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    setInstanceByte
 * Signature: (BLjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnireflection_bindings_JNIReflection_setInstanceByte
        (JNIEnv *, jclass, jbyte, jobject, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    getInstanceShort
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_com_jnireflection_bindings_JNIReflection_getInstanceShort
        (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    setInstanceShort
 * Signature: (SLjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnireflection_bindings_JNIReflection_setInstanceShort
        (JNIEnv *, jclass, jshort, jobject, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    getInstanceInt
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jnireflection_bindings_JNIReflection_getInstanceInt
        (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    setInstanceInt
 * Signature: (ILjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnireflection_bindings_JNIReflection_setInstanceInt
        (JNIEnv *, jclass, jint, jobject, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    getInstanceLong
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_jnireflection_bindings_JNIReflection_getInstanceLong
        (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    setInstanceLong
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnireflection_bindings_JNIReflection_setInstanceLong
        (JNIEnv *, jclass, jlong, jobject, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    getInstanceFloat
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_com_jnireflection_bindings_JNIReflection_getInstanceFloat
        (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    setInstanceloat
 * Signature: (FLjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnireflection_bindings_JNIReflection_setInstanceloat
        (JNIEnv *, jclass, jfloat, jobject, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    getInstanceDouble
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_com_jnireflection_bindings_JNIReflection_getInstanceDouble
        (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    setInstanceDouble
 * Signature: (DLjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnireflection_bindings_JNIReflection_setInstanceDouble
        (JNIEnv *, jclass, jdouble, jobject, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    getInstanceBoolean
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jnireflection_bindings_JNIReflection_getInstanceBoolean
        (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    setInstanceBoolean
 * Signature: (ZLjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnireflection_bindings_JNIReflection_setInstanceBoolean
        (JNIEnv *, jclass, jboolean, jobject, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    getInstanceChar
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)C
 */
JNIEXPORT jchar JNICALL Java_com_jnireflection_bindings_JNIReflection_getInstanceChar
        (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    setInstanceChar
 * Signature: (CLjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnireflection_bindings_JNIReflection_setInstanceChar
        (JNIEnv *, jclass, jchar, jobject, jstring, jstring);

/*
 * Class:     com_jnireflection_bindings_JNIReflection
 * Method:    getInstances
 * Signature: (Ljava/lang/String;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jnireflection_bindings_JNIReflection_getInstances
        (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
